# Generated by Django 5.0.4 on 2024-05-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('decks', models.ManyToManyField(blank=True, related_name='subject_set', to='flashcards.deck')),
            ],
        ),
    ]
