# Generated by Django 5.0.4 on 2024-06-01 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_alter_deck_name_alter_flashcard_question_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
