# Generated by Django 5.0.4 on 2024-06-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_delete_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='lastTimeRememberedAt',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
